#! /usr/bin/env bash

set -ex

ALACRITTY_DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
ALACRITTY_RELEASE=alacritty_terminal_v0.16.0
ALACRITTY_INSTALL_DIR=/usr/local/bin

sudo apt install -y\
  cargo\
  cmake\
  libfontconfig1-dev\
  libfreetype6-dev\
  libxcb-xfixes0-dev\
  libxkbcommon-dev\
  pkg-config\
  python3

if [ ! -d ${ALACRITTY_DIR} ]; then
  git clone -b ${ALACRITTY_RELEASE} https://github.com/alacritty/alacritty.git ${ALACRITTY_DIR} || true
fi

$(cd alacritty; cargo build --release)
sudo cp ${ALACRITTY_DIR}/target/release/alacritty ${ALACRITTY_INSTALL_DIR}

sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator  ${ALACRITTY_INSTALL_DIR}/alacritty 50

mkdir -p ${HOME}/.config/alacritty/
cp ${ALACRITTY_DIR}/alacritty.yml ${HOME}/.config/alacritty
