#! /usr/bin/env bash

set -ex

ALACRITTY_DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/alacritty"
ALACRITTY_RELEASE=v0.13.2
ALACRITTY_INSTALL_DIR=/usr/local/bin
ALACRITTY_CONFIG_DIR=${HOME}/.config/alacritty
ALACRITTY_THEME_DIR=${ALACRITTY_CONFIG_DIR}/themes/

# use Hack Nerd Font for the terminal
wget "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Hack.zip" -O /tmp/Hack.zip
sudo unzip /tmp/Hack.zip /usr/local/share/fonts/

sudo apt install -y\
  cargo\
  cmake\
  libfontconfig1-dev\
  libfreetype6-dev\
  libxcb-xfixes0-dev\
  libxkbcommon-dev\
  pkg-config\
  python3

if [ ! -d ${ALACRITTY_DIR} ]; then
  git clone -b ${ALACRITTY_RELEASE} https://github.com/alacritty/alacritty.git ${ALACRITTY_DIR} || true
fi

$(cd alacritty; cargo build --release)
sudo cp ${ALACRITTY_DIR}/target/release/alacritty ${ALACRITTY_INSTALL_DIR}

sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator  ${ALACRITTY_INSTALL_DIR}/alacritty 50

if [ ! -d ${ALACRITTY_CONFIG_DIR} ]; then
  mkdir -p ${ALACRITTY_CONFIG_DIR}

  if [ ! -d ${ALACRITTY_THEME_DIR} ]; then
    mkdir -p ${ALACRITTY_THEME_DIR}
    git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
  fi

  cp ${ALACRITTY_DIR}/alacritty.toml ${ALACRITTY_CONFIG_DIR}
fi
