#! /usr/bin/env bash

set -ex

SCRIPT_DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
REPO_DIR=${SCRIPT_DIR}/alacritty
RELEASE=v0.13.2
INSTALL_DIR=/usr/local/bin

# use Hack Nerd Font for the terminal
FONTS_DIR=/usr/local/share/fonts/
wget "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Hack.zip" -O /tmp/Hack.zip
sudo mkdir -p ${FONTS_DIR}
sudo unzip -o /tmp/Hack.zip -d ${FONTS_DIR}

DEPENDENCIES="
  cargo
  cmake
  libfontconfig1-dev
  libfreetype6-dev
  libxcb-xfixes0-dev
  libxkbcommon-dev
  pkg-config
  python3
"

source /etc/os-release
if command -v apt; then
  sudo apt install -y ${DEPENDENCIES}
elif command -v pacman; then
  sudo pacman -S --noconfirm ${DEPENDENCIES}
else
  echo "Unsupported Linux distro: ${ID}"
  exit 1
fi

if [ ! -d ${REPO_DIR} ]; then
  git clone -b ${RELEASE} https://github.com/alacritty/alacritty.git ${REPO_DIR} || true
fi

$(cd ${REPO_DIR}; cargo build --release)
sudo cp ${REPO_DIR}/target/release/alacritty ${INSTALL_DIR}

sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator ${INSTALL_DIR}/alacritty 50
