#!/usr/bin/env bash

set -e

LSP_NAME=lua-language-server

curl -sL https://github.com/LuaLS/${LSP_NAME}/releases/download/3.17.1/${LSP_NAME}-3.17.1-linux-x64.tar.gz\
  | tar zxf - --one-top-level=${HOME}/.local/${LSP_NAME}
ln -sf ${HOME}/.local/${LSP_NAME}/bin/${LSP_NAME} ${HOME}/.local/bin/${LSP_NAME}
