#! /usr/bin/env bash

set -e

STAMP_FILE="/tmp/install_dependencies.stamp "
if [ ! -f ${STAMP_FILE}]
then
    echo "Run install_dependencies first"
    exit 1
fi

DOTFILES_DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

# Never need these
rm -rf ${HOME}/{Documents,Music,Pictures,Public,Templates,Videos}

${DOTFILES_DIR}/nvim/setup ${DOTFILES_DIR}/nvim/
${DOTFILES_DIR}/zsh/setup ${DOTFILES_DIR}/zsh/

if command -v alacritty; then
  ${DOTFILES_DIR}/alacritty/configure
fi

function add-dotfile-as-source () {
    # Append a line in `src` to source the `dst` file
    local src=$1
    local dst=$2
    local cmd="source ${src}"

    grep "${cmd}" ${dst} &> /dev/null || echo ${cmd} >> ${dst}
}

add-dotfile-as-source ${DOTFILES_DIR}/tmux/.tmux.conf ${HOME}/.tmux.conf
add-dotfile-as-source ${DOTFILES_DIR}/zsh/.zshrc ${HOME}/.zshrc
add-dotfile-as-source ${DOTFILES_DIR}/aliases ${HOME}/.zshrc
