#! /usr/bin/env bash

set -ex

apt -y update
apt -y install \
  build-essential \
  curl \
  ddate \
  exuberant-ctags \
  git \
  python3-pip \
  tmux \
  vim \
  xclip \
  zsh \
;
apt -y autoremove

pip3 install \
  ipython \
;

# Use Python3
update-alternatives --install /usr/bin/python python /usr/bin/python3 1
