#! /usr/bin/env bash

set -ex

sudo apt update -y
sudo apt install -y\
  ddate\
  neofetch\
  trash-cli\
  tree

sudo apt -y autoremove

echo "neofetch" >> ${HOME}/.zshrc
echo "ddate" >> ${HOME}/.zshrc
