# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "public_network", bridge: "wlp1s0"
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 4
  end
  config.vm.provision "shell", privileged: false, path: "./provision_dotfiles.sh"
  # config.vm.provision "shell", privileged: false, path: "./install_rust.sh", args: ".zshrc"
  config.vm.provision "shell", path: "./install_docker.sh"
end
