#! /usr/bin/env bash

set -ex

if ! dpkg -l git vim &> /dev/null
then
    echo "Run install_dependencies first"
    exit 1
fi

PLUGIN_START_DIR=${HOME}/.vim/pack/vendor/start
mkdir -p ${PLUGIN_START_DIR}
git clone https://github.com/preservim/nerdtree.git ${PLUGIN_START_DIR}/nerdtree

mkdir ${HOME}/.vim/plugin
git clone https://github.com/jiangmiao/auto-pairs.git /tmp/auto-pairs
cp /tmp/auto-pairs/plugin/auto-pairs.vim ${HOME}/.vim/plugin
