#!/usr/bin/env bash

set -e

# TODO: At time of writing, v12.0+ have issues with double key inputs in Alacritty,
#       so bump version when this gets fixed
VERSION=v0.11.7

arch=$(uname -m)
if [[ "$arch" == "x86_64" ]]; then
    PKG_NAME="nvim-linux-x86_64"
elif [[ "$arch" == "aarch64" ]]; then
    PKG_NAME="nvim-linux-arm64"
fi

ARCHIVE=${PKG_NAME}.tar.gz
wget https://github.com/neovim/neovim/releases/download/${VERSION}/${ARCHIVE} -P /tmp
tar xzf /tmp/${ARCHIVE} -C /usr/local/

ln -sf /usr/local/${PKG_NAME}/bin/nvim /usr/local/bin/nvim
ln -sf /usr/local/${PKG_NAME}/bin/nvim /usr/bin/vi
ln -sf /usr/local/${PKG_NAME}/bin/nvim /usr/bin/vim

# Nodejs v22+ needed for Copilot plugin
curl -fsSL https://deb.nodesource.com/setup_25.x | sudo bash -
apt install -y nodejs
