#!/usr/bin/env bash

set -ex

NVIM_DIR=${1:-${HOME}/dotfiles/nvim}
NVIM_CONFIG_DIR="${HOME}/.config/nvim/"

mkdir -p ${NVIM_CONFIG_DIR}
cp -rf ${NVIM_DIR}/lua/ ${NVIM_CONFIG_DIR}/lua/

echo 'vim.cmd("source ${HOME}/dotfiles/nvim/init.lua")' > ${NVIM_CONFIG_DIR}/init.lua
