#! /usr/bin/env bash

set -ex

if ! dpkg -l terminator &> /dev/null
then
    echo "Run install_dependencies first"
    exit 1
fi

DIR=$1

mkdir -p ${HOME}/.config
cp ${DIR}/terminator/config ${HOME}/.config/terminator
