#! /usr/bin/env bash

set -ex

SOURCE_DIR=$1

# ZSH tools and plugins
## Oh My Zsh
OH_MY_ZSH_DIR=${HOME}/.oh-my-zsh
if [ ! -d ${OH_MY_ZSH_DIR} ]
then
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended"
  cp ${SOURCE_DIR}/themes/* ${OH_MY_ZSH_DIR}/themes/
fi

## zsh-autosuggestions
ZSH_AUTOSUGGESTIONS_DIR=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
if [ ! -d ${ZSH_AUTOSUGGESTIONS_DIR} ]
then
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_AUTOSUGGESTIONS_DIR}
fi

ZSH_SYNTAX_HIGHLIGHTING_DIR=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
if [ ! -d ${ZSH_SYNTAX_HIGHLIGHTING_DIR} ]
then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_SYNTAX_HIGHLIGHTING_DIR}
fi

FZF_DIR=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/fzf
if [ ! -d ${FZF_DIR} ]
then
    git clone --depth 1 https://github.com/junegunn/fzf.git ${FZF_DIR} && yes | ${FZF_DIR}/install
fi
